name: windows_store
description: A flutter plugin for retrieving license information from Microsoft Store apps.
version: 0.1.0
repository: https://github.com/SongbookPro/flutter_windows_store

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^22.4.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsStorePluginCApi
