// Autogenerated from Pigeon (v22.4.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace windows_store {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class WindowsStoreApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class StoreAppLicenseInner {
 public:
  // Constructs an object setting all fields.
  explicit StoreAppLicenseInner(
    bool is_active,
    bool is_trial,
    const std::string& sku_store_id,
    const std::string& trial_unique_id,
    int64_t trial_time_remaining);

  bool is_active() const;
  void set_is_active(bool value_arg);

  bool is_trial() const;
  void set_is_trial(bool value_arg);

  const std::string& sku_store_id() const;
  void set_sku_store_id(std::string_view value_arg);

  const std::string& trial_unique_id() const;
  void set_trial_unique_id(std::string_view value_arg);

  int64_t trial_time_remaining() const;
  void set_trial_time_remaining(int64_t value_arg);


 private:
  static StoreAppLicenseInner FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowsStoreApi;
  friend class PigeonInternalCodecSerializer;
  bool is_active_;
  bool is_trial_;
  std::string sku_store_id_;
  std::string trial_unique_id_;
  int64_t trial_time_remaining_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class WindowsStoreApi {
 public:
  WindowsStoreApi(const WindowsStoreApi&) = delete;
  WindowsStoreApi& operator=(const WindowsStoreApi&) = delete;
  virtual ~WindowsStoreApi() {}
  virtual void GetAppLicenseAsync(std::function<void(ErrorOr<StoreAppLicenseInner> reply)> result) = 0;

  // The codec used by WindowsStoreApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `WindowsStoreApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowsStoreApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowsStoreApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  WindowsStoreApi() = default;

};
}  // namespace windows_store
#endif  // PIGEON_MESSAGES_G_H_
